# Generated by Django 5.2.1 on 2025-05-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
