# Generated by Django 5.2.1 on 2025-05-30 18:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_location_user_address_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be an Egyptian number starting with 010, 011, 012, or 015.', regex='^01[0125][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
